pipeline:
  docker:
    image: plugins/docker
    when:
      branch:
        - prod
      event: push
      status: success
    registry: https://registry.abakus.no
    repo: registry.abakus.no/webkom/lego-webapp
    secrets: [docker_username, docker_password, sentry_auth_token]
    tags:
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    build_args:
      - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
      - SENTRY_AUTH_TOKEN
      - SENTRY_ORG=webkom
      - SENTRY_PROJECT=lego-webapp
      - SENTRY_URL=https://sentry.abakus.no/
