name: LEGO frontend

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!prod'

jobs:
  setup:
    name: Setup environment
    runs-on: ubuntu-latest

    steps:
    - name: List github dir and printenv
      run: |
        printenv
        ls -al /github

    - name: Checkout commit
      uses: actions/checkout@v1

    - name: Set up Node 11.x
      uses: actions/setup-node@v1
      with:
        node-version: '11.x'

    - name: Install dependencies
      run: yarn --forzen-lockfile

    - name: List github dir and printenv
      run: |
        printenv
        ls -al /github

    - name: Copy to work dir
      run: |
        cp -vr ./node_modules /github
        ls -al /github
        ls -al /github/node_modules

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: List github dir
      run: ls -al /github

    - name: Checkout commit
      uses: actions/checkout@v1

    - name: Set up Node 11.x
      uses: actions/setup-node@v1
      with:
        node-version: '11.x'

    - name: Build server
      run: yarn build:server

    - name: Build client
      run: yarn build:client


  tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout commit
      uses: actions/checkout@v1

    - name: Set up Node 11.x
      uses: actions/setup-node@v1
      with:
        node-version: '11.x'

    - name: Run tests
      run: yarn test

  linting:
    name: Run linting
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout commit
      uses: actions/checkout@v1

    - name: Set up Node 11.x
      uses: actions/setup-node@v1
      with:
        node-version: '11.x'

    - name: Run linting
      run: yarn lint

  flow:
    name: Run flow
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout commit
      uses: actions/checkout@v1

    - name: Set up Node 11.x
      uses: actions/setup-node@v1
      with:
        node-version: '11.x'

    - name: Run flow
      run: yarn flow

  cypress:
    name: Run Cypress
    runs-on: ubuntu-latest
    needs: setup

    services:
      postgres:
        image: postgres:9.5
        ports:
        - 5432:5432
        env:
          POSTGRES_USER: lego
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      thumbor:
        image: apsl/thumbor:latest
        ports:
        - 8001:8000
        env:
          SECURITY_KEY: lego-dev
          MAX_WIDTH: 1000
          MAX_HEIGHT: 800
          QUALITY: 98
          ALLOW_UNSAFE_URL: 0
          ALLOW_OLD_URLS: 0
          AWS_ACCESS_KEY_ID: lego-dev
          AWS_SECRET_ACCESS_KEY: lego-dev
          TC_AWS_LOADER_BUCKET: lego
          TC_AWS_REGION: us-east-1
          TC_AWS_ENDPOINT: http://localhost:9000
          LOADER: tc_aws.loaders.s3_loader
      redis:
        image: redis
        ports:
        - 6379:6379

    steps:
    - name: Checkout commit
      uses: actions/checkout@v1

    - name: Set up Node 11.x
      uses: actions/setup-node@v1
      with:
        node-version: '11.x'

    - name: Setup MinIO
      uses: ./.github/actions/setup-minio
      env:
        MINIO_ACCESS_KEY: lego-dev
        MINIO_SECRET_KEY: lego-dev
